function output = choose_dialog_mass(dlg_title, position)

% This dialog is shown after a ROI has been drawn

if iscell(dlg_title)
    dlg_title = cell2mat(dlg_title);
end

x_pos = position(1);
y_pos = position(2)-100;

%d = dialog('Position',[300 300 350 150],'Name',dlg_title);
d = dialog('Units','pixels','Position',[x_pos y_pos 350 150],'Name',dlg_title);

movegui(d,'center') % A. I. mod

txt_shape = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 100 130 20],...
    'String','Select mass shape:');

popup_shape = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[20 90 100 20],...
    'String',{'oval';'round';'irregular'},...
    'Callback',@popup_callback,...
    'Tag','shape'); 

txt_margin = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 80 130 20],...
    'String','Select mass margin:');

popup_margin = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[20 70 100 20],...
    'String',{'circumscribed';'obscured';'microlobulated';'indistinct';'spiculated'},...
    'Callback',@popup_callback,...
    'Tag','margin');

txt_density = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 60 130 20],...
    'String','Select mass density:');

popup_density = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[20 50 100 20],...
    'String',{'high';'equal';'low';'fat-containing'},...
    'Callback',@popup_callback,...
    'Tag','density');

btn = uicontrol('Parent',d,...
    'Position',[130 10 70 25],...
    'String','Close',...
    'Callback','delete(gcf)');

align([txt_shape popup_shape],'Fixed',10,'Top');
align([txt_margin popup_margin],'Fixed',10,'Middle');
align([txt_density popup_density],'Fixed',10,'Bottom');
align(btn,'Center','None');

output.choice_shape = 'oval';
output.choice_margin = 'circumscribed';
output.choice_density = 'high';

% Wait for d to close before running to completion
uiwait(d);

       function popup_callback(popup,~)
          idx = popup.Value;
          popup_items = popup.String;
          if strcmp(popup.Tag,'shape')
             output.choice_shape = char(popup_items(idx,:));
          elseif strcmp(popup.Tag,'margin')
             output.choice_margin = char(popup_items(idx,:));
          elseif strcmp(popup.Tag,'density')
             output.choice_density = char(popup_items(idx,:));
          end
       end
   
end