function msg = get_licence_text() % Antti mod 24.2.2020

% Get tool licence

%ver = get_version();

msg = {'{\fontsize{14}\bfMammogram Annotation Tool.}'; ...
''; ...
'Created with MATLAB R2020a. Copyright (c) 1984-2020 The MathWorks, Inc.'; ...
''; ...
'{\fontsize{12}\bfLicense:}'; ...
''; ...
'MIT License'; ...
''; ...
'Copyright (c) 2019 Research Unit of Medical Imaging, Physics and Technology'; ...
'Copyright (c) 2019 Antti Isosalo'; ...
'Copyright (c) 2019 Satu Inkinen'; ...
'Copyright (c) 2019 Miika T. Nieminen'; ...
' '; ...
'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:'; ...
''; ...
'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.'; ...
''; ...
'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'
};

% Usage:
% CreateStruct.Interpreter = 'tex';
% CreateStruct.WindowStyle = 'non-modal';
% msgbox(msg,'Title','help',CreateStruct);

end
